### ISSUE TITLE
Retrofit + adapters + DI

### ISSUE THREAD

**Issue by victorvicari** [Lider123/mobile_desiregallery#86]
I saw that you're using the `Retrofit`, although you are also using custom `serialization`. Why? Maybe add the `GsonConverter` when you build the `Retrofit instance`. This will make your code much more readable.
Maybe add some `dependecy injection` as well. Since you are using `Kotlin`... maybe add the `Koin` library. The setup is far more easier than `Dagger 2`.
I can help you with it. Let me know if you are interested.

**Comment by Lider123** [comment]
Hello. I use custom serialization because of REST Firestore API, which has specific json structure.

**Comment by Lider123** [comment]
Actually I didn't suppose anyone to find this repository.

**Comment by Lider123** [comment]
And what is the difference between my solution and the one in article below?
https://www.woolha.com/tutorials/retrofit-2-define-custom-gson-converter-factory

**Comment by victorvicari** [comment]
I've just asked out of curiosity. But I did understand what were your purpose. If you are interest in some help, email me.
